### PR TITLE
ENH: Add Multikernel / banded example

### PR DESCRIPTION
**Pull request by adelavega**
Adding an example using `himayala`'s `MultipleKernelRidgeCV` on MFCC and Mel spectrogram features.

This example follows up from the previous Ridge regression example.

### CODE REVIEW

**Comment by adelavega** [comment]
@rbroc I added a banded example

Let me know what you think if you get a chance

**Comment by rbroc** [comment]
had a quick look - i like the idea of having the same feature sets as in the other example.

two comments:
- here, the result scores have 3 dimensions (folds x bands x voxels, I guess) -- my guess is that performances for each band are estimated separately? is there a way to combine / aggregate them properly?
- it'd be great to also show a score map, if we find a meaningful way to aggregate them -- or just showing separate maps for each band?

**Comment by adelavega** [comment]
I believe that can be done! They do it in the himalaya example.

I think the issue for this feature set is that there wasn't that much meaningful difference between the feature sets. 

But I think for an initial example this might be OK.

Ideally we find one where the differences are greater.

**Comment by adelavega** [comment]
Okay, I added plots by band, and restricted to STG ROI to make the computation go faster.

Don't have much more time to spend on this, so I think I'll merge as is, and hopefully it inspires some users!

**Pull request merged**
